name: ci-sonarcloud
on:
  pull_request:
    branches:
      - master

jobs:
  run-ci:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
        node-version: 20.11.1
      - run: npm ci
      - run: npm test